#just for tac
statistics=true
job=post_to_post_test
jobVersion=0.1
date=2024-07-30 071236988
contextName=Default
jobId=_nneWoE43Ee-Dhr2Vipv99A
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=LOCAL_PROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=